version: '3.7'

services:
  influxdb:
    hostname: influxdb
    env_file: .env
    image: influxdb
    volumes:
      - ./influxdb/persistent-data:/bitnami/influxdb
    ports:
      - "80:8086"

  driver:
    image: registry.hub.docker.com/crocokyle/powmr-driver:main
    volumes:
      - .:/driver
    command: /bin/sh -c 'python /driver/main.py'