version: '3.7'

services:
  influxdb:
    restart: always
    hostname: influxdb
    env_file: .env
    image: influxdb
    volumes:
      - ./influxdb/persistent-data:/bitnami/influxdb
    ports:
      - "80:8086"

  driver:
    restart: always
    image: registry.hub.docker.com/crocokyle/drivers:main
    volumes:
      - .:/driver
      - /var/run/dbus:/var/run/dbus:z
    command: /bin/sh -c 'python /driver/main.py'
    devices:
      - ${COM_PORT}:/dev/ttyUSB0