version: '3.7'

services:
  influxdb:
    restart: always
    hostname: influxdb
    env_file: .env
    image: influxdb
    volumes:
      - ./influxdb/persistent-data:/bitnami/influxdb
    ports:
      - "80:8086"

  driver:
    restart: always
    image: powmr-driver:rpi
    volumes:
      - .:/dashboard
      - /var/run/dbus:/var/run/dbus
    command: /bin/sh -c 'python /dashboard/main.py'
    devices:
      - ${COM_PORT}:/dev/ttyUSB0